### ISSUE TITLE
Rocket Chat throws error "Request Entity too Large" when uploading a file which is larger than 1 MB

### ISSUE THREAD

**Issue by gruenerBogen** [serlo/infrastructure-env-production#18]
When you upload a file which has a size > 1MB, Rocket Chat shows the Error "Request Entity too Large".

How to reproduce this issue:
1. Go to https://community.serlo.org
2. Upload a file with a file size > 1 MB

So far, the following considerations have been made:
The error message is probably showing an underlying HTTP error 413, which is thrown if the request sent to the server is too large. The Rocket Chat settings allow an upload of files up to 100 MB, so this shouldn't be the problem.
Thus the problem lies in the kubernetes configuration linking the Rocket Chat container and the Internet. As incoming traffic is sorted by domain name to different docker containers, this sorting point could be the point which produces this issue.

**Comment by inyono** [comment]
Hey @gruenerBogen. Thanks for the extensive research. Currently swamped with other stuff, going to address that soon, though.

**Comment by inyono** [comment]
I increased the body size limit to 5 Megabyte. Let me know if we need a bigger limit for some reason.
