### ISSUE TITLE
Upgrade kratos to version 1 and fix broken accounts

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/infrastructure-env-production#38]
The latest release of ory kratos fixed a memory leak that may be the reason why sometimes our registration webhook doesn't work (leading to broken accounts, see https://github.com/serlo/infrastructure-modules-shared/issues/43). We need to upgrade it and at the same token fix the accounts that are broken.

**Comment by eliflores** [comment]
Fixed in https://github.com/serlo/infrastructure-env-staging/pull/44 & https://github.com/serlo/infrastructure-env-production/pull/39 💚
