### ISSUE TITLE
Redis sometimes doesn't work

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/infrastructure-env-production#42]
and it makes the api fail.

example log:
`[ioredis] Unhandled error event: Error: connect ECONNREFUSED 10.1.1.223:6379    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"`

- [ ] make redis more robust

**Comment by kulla** [comment]
Do you have an idea: how?

**Comment by kulla** [comment]
@hugotiburtino thanks for helping - giving more memory was the solution
