### ISSUE TITLE
Handle SSL in all exposed services

### ISSUE THREAD

**Issue by inyono** [serlo/infrastructure-env-production#6]
We recently noticed that our Cloudflare config isn't correct. We currently have [SSL Mode](https://developers.cloudflare.com/ssl/origin/ssl-modes/) Flexible because we have services that don't handle HTTPS requests correctly. Unfortunately, this also means that services that could handle HTTPS requests still get HTTP requests (i.e. we currently only encryt the request between end user and cloudflare, the request from cloudflare to our actual servers is via HTTP). We should switch to [SSL Mode](https://developers.cloudflare.com/ssl/origin/ssl-modes/) Full again and check if all services work correctly.

I already added module `modules-shared/tls-self-signed-certs` that generates a self-signed certificate for the specified domain / wildcard via terraform to make setup easier. But we still need to configure the ingress resources correctly (similar to what we do in serlo.org already). We should probably be able to abstract that away into its own module that handles everything (i.e. only pass domain and the ip of the service) so that our services don't need to think about that at all. Might also be a good opportunity to refactor `modules-shared/ingress-nginx` since that seems complicated and maybe is now correctly supported by k8s itself (at least it seems that way in the helm handling we had)

**Comment by kulla** [comment]
Update from meeting yesterday: We think that this import and SSL should be implemented. However, if it takes time to implement and prohibits you from working on finishing other projects we shall do it afterwards in a refractoring phase.

**Comment by inyono** [comment]
Missing:
- [ ] community.serlo.org
- [ ] stats.serlo.org
