### ISSUE TITLE
Replace legacy cronjobs with k8s cronjobs

### ISSUE THREAD

**Issue by inyono** [serlo/infrastructure-env-production#7]
We should replace our custom cronjobs (i.e. docker images that implement cronjobs itself and are running all the time) to k8s cronjobs. Makes handling of those easier (e.g. to run them manually out of schedule) & needs less resources (because k8s handles the cron stuff and we don't have a pod that runs all the time)

**Comment by kulla** [comment]
For the KPI we have https://github.com/serlo/p_data-analysis-and-kpis/issues/132 as a follow up. When others want to implement it:

* https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/ - docs about the feature
* Place where it is already implemented: https://github.com/serlo/infrastructure-modules-serlo.org/blob/master/server/main.tf#L199

A follow up would be to find all modules (except those from the KPI project) which need to be updated...

**Comment by inyono** [comment]
Apart from KPI, it’s only team overview page

**Comment by hugotiburtino** [comment]
Already live. See https://github.com/serlo/infrastructure-modules-serlo.org/pull/25

KPI issue is still open though.
