### ISSUE TITLE
Review/Implement Alerts and Monitoring 

### ISSUE THREAD

**Issue by ghost** [serlo/infrastructure-env-production#8]
to get informed, when the following applications are down:
- athene2-app
- editor-renderer-app
- grafana-app
- legacy-editor-renderer-app	
- nginx-ingress-app
- varnish-app

**Comment by hugotiburtino** [comment]
most of these projects aren't critical for serlo.org (like grafana, if it's down - as it seems to be now :D, someone will tell us and we take a look at it). Others were critical but after migration aren't anymore. Others, like nginx-ingress, we'll get indirectly through 3rd party monitoring. So it doesn't worth the work
